### ISSUE TITLE
Bug: Unable to create new card from a template

### ISSUE THREAD

**Issue by nishantwrp** [mattermost/focalboard#2041]
## Steps to reproduce the behavior

1. Try to create a new card from a template
2. See error

## Screenshots

I get this card when I try to create a new card from a pre-existing template.

<img width="998" alt="Screenshot 2021-11-29 at 11 34 47 PM" src="https://user-images.githubusercontent.com/36989112/143920159-d921892d-5863-426b-bcbc-109dd018832a.png">

## Edition and Platform

 - Edition: Personal Server
 - Version: v0.11.0
 - Browser and OS: Safari & MacOS

## Additional context

This issue was created by me before in #1888 but re-creating because this is still not fixed for me.

**Comment by chenilim** [comment]
@ogi-m, are you able to repro this with v0.11 Personal Server? It didn't repro for me with the plugin (Community Server) or main build. However, I did find and file an issue with the template description not being persisted (#2042).

**Comment by nishantwrp** [comment]
Oh yes actually the error "The card doesn't exist ..." it appears for a split second and I can edit a card but template description and content is not copied automatically to the new card.

**Comment by ogi-m** [comment]
@nishantwrp Does that mean we can close this issue, since the card does get created but without the description (which is covered by #2042) ?

**Comment by nishantwrp** [comment]
Yup, just to point out. It's not just description. It's other content, title as well. Just the status property value was persisted.

**Comment by harshilsharma63** [comment]
@nishantwrp can you please try this on [v0.12 RC1](https://github.com/mattermost/focalboard/releases/tag/v0.12.0-rc1)? This was fixed yesterday by #2017.

https://user-images.githubusercontent.com/18575143/148501853-b062bd52-1fbe-48d6-a248-a0901ce3c9f4.mp4

**Comment by nishantwrp** [comment]
Hi @harshilsharma63, the description and content works fine now. But title is not still persisted. Not sure if that intensional.

**Comment by sbishel** [comment]
Fixed in v0.12.0

**Comment by ogi-m** [comment]
Thanks @nishantwrp, the title behaviour is expected.
