### ISSUE TITLE
Bug: Reordering board columns is broken

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#420]
**Steps to reproduce the behavior:**
1. Open a board view with multiple (4+) columns
2. Drag the 4th column to the 2nd column
3. New order is: 1, 3, 4, 2

**Expected behavior:**
New order should be: 1, 4, 2, 3

**Screenshots:**
Before drag (4th column to 2nd):
<img width="1395" alt="before drag" src="https://user-images.githubusercontent.com/46905241/118540027-074ae380-b705-11eb-8c92-a54b9af42bd9.png">

After drag:
<img width="1394" alt="after drag" src="https://user-images.githubusercontent.com/46905241/118540050-0e71f180-b705-11eb-9bfb-3ec9722731e9.png">

**Platform:**
 - Chrome 89 on macOS 10.15.7

**Additional context:**
Also check dragging the "no status" column. Handling may be different.
Also check the undo/redo of dragging columns.

**Comment by harshilsharma63** [comment]
I'm working on this one.

**Comment by harshilsharma63** [comment]
FIxed with #537

**Comment by chenilim** [comment]
@harshilsharma63, I'm still seeing unexpected behavior dragging columns on v0.8.1:

https://user-images.githubusercontent.com/46905241/126599823-98f60734-485c-4de1-be1a-8affc5d3eb45.mov

Repros on the community server with [this board](https://community.mattermost.com/plugins/focalboard/workspace/qgsck6cts3fwpqwyjiupjm5cde?id=0e57479f-c05a-4191-8d7d-7a23a4a6ffd7&v=0dcb9125-cf17-498e-88b6-bfd397d83bae).

Please investigate, and unless it's a high-risk fix, let's cherry pick it for `release-0.8.0`. Thanks.

**Comment by chenilim** [comment]
May be a dup of #740?
